use_wandb: 0  # Whether to use Weights & Biases for logging (1) or not (0)
wandb_project: ${oc.env:WANDB_PROJECT} # Name of the Weights & Biases project
wandb_entity: ${oc.env:WANDB_ENTITY} # Name of the Weights & Biases entity
wandb_cache_dir: ${oc.env:WANDB_CACHE_DIR} # Path to the Weights & Biases cache directory
wandb_dir: ${oc.env:WANDB_DIR} # Path to the Weights & Biases directory
