name: cp2
channels:
  - conda-forge
  - pytorch
dependencies:
  - python=3.10
  - pip
  - matplotlib
  - notebook
  - numpy
  - pandas
  - pillow
  - pytest
  - pyyaml
  - pytorch
  - torchvision
  - scipy
  - tqdm
  - wandb
  - pip:
      - equiadapt
      - hydra-core
      - matplotlib
      - omegaconf
      - pandas
      - pickle5
      - python-dotenv
      - pytorch-lightning
      - scikit-learn
      - torch-geometric
      - torchcp
      - torchmetrics
      - torchsort
      - transformers